version: '3.8'

services:
  evdms-db:
    image: mysql:8.0
    container_name: ev_dms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ev_dms
    ports:
      - "3307:3306"
    volumes:
      - evdms-data:/var/lib/mysql

#  evdms-app:
#    build: .
#    container_name: evdms-app
#    depends_on:
#      - evdms-db
#    ports:
#      - "8081:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://evdms-db:3306/evdms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 123456
#
volumes:
  evdms-data:
