server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/login,/logout,/post-login,/admin/**,/dealer/**,/evm/**,/manager/**,/staff/**,/css/**,/js/**,/image/**,/webjars/**
          filters:
            - StripPrefix=0

        - id: crm-service
          uri: http://localhost:9001
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1

        - id: catalog-service
          uri: http://localhost:9002
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1

        # Route tá»›i inventory-service (REST API)
        - id: inventory-service-api
          uri: http://localhost:9003
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://localhost:9004
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

        - id: sales-service
          uri: http://localhost:9005
          predicates:
            - Path=/sales/**
          filters:
            - StripPrefix=1

        - id: report-service
          uri: http://localhost:9006
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
